### ISSUE TITLE
俊哥你好，这个怎么用呀，没有找到插件安装包，是需要有开发经验配置什么东西吗

### ISSUE THREAD

**Issue by sanqiushili** [leadream/figma-viewer-chrome-plugin#1]
俊哥你好，这个怎么用呀，没有找到插件安装包，是需要有开发经验配置什么东西吗

**Comment by leadream** [comment]
@sanqiushili 需要开发经验，关于如何开发和使用请看 README。
https://github.com/leadream/figma-viewer-chrome-plugin/blob/main/README.md
